Repository VirtusLab/besom, pull requests merged in 2023-09, with the labels that each got.

#143 Update ci.yml
  .github/workflows/ci.yml
Labels: area/testing

#129 Add a simple integration test for besom
  .github/workflows/ci.yml
  .gitignore
  Justfile
  README.md
  besom-cats/project.scala
  besom-cats/src/main/scala/runtime.scala
  besom-zio/project.scala
  besom-zio/src/main/scala/runtime.scala
  codegen/src/CodeGen.scala
  codegen/src/Main.scala
  compiler-plugin/project.scala
  core/project.scala
  core/src/main/scala/besom/future.scala
  experimental/project.scala
  experimental/src/main/scala/besom/liftoff.scala
  integration-tests/.scalafmt.conf
  integration-tests/project.scala
  integration-tests/src/test/resources/compilerplugintest.scala
  integration-tests/src/test/resources/purrl-example/Pulumi.yaml
  integration-tests/src/test/resources/purrl-example/run.scala
  integration-tests/src/test/resources/random-example/Pulumi.yaml
  integration-tests/src/test/resources/random-example/run.scala
  integration-tests/src/test/resources/tls-example/Pulumi.yaml
  integration-tests/src/test/resources/tls-example/run.scala
  integration-tests/src/test/scala/besom/integration/CompilerPluginTest.scala
  template/default/project.scala
  template/kubernetes/project.scala
Labels: area/testing

#142 Update README.md with IDE setup instructions
  .github/workflows/ci.yml
  README.md
Labels: area/docs, area/tooling, kind/internal

#153 Use compiler plugin in templates
  .gitignore
  experimental/project.scala
  template/default/Main.scala
  template/default/project.scala
  template/kubernetes/project.scala
Labels: area/docs, impact/no-changelog-required

#154 Update ci.yml
  .github/workflows/ci.yml
Labels: area/testing, impact/cost

#157 Allow only same repo PRs
  .github/workflows/ci.yml
  .github/workflows/test-website.yml
  .github/workflows/website.yml
Labels: impact/security, area/testing, impact/cost

#151 Make the ToFuture instance for ZIO polymorphic over the error type to…
  besom-cats/project.scala
  besom-zio/project.scala
  besom-zio/src/main/scala/runtime.scala
  integration-tests/src/test/resources/tls-example/run.scala
Labels: kind/improvement, impact/usability, area/api

#174 Publish improvements
  Justfile
  scripts/Packages.scala
Labels: kind/enhancement, impact/reliability, area/build

#127 Docs
  LICENSE
  website/docs/apply_methods.md
  website/docs/architecture.md
  website/docs/compiler_plugin.md
  website/docs/components.md
  website/docs/constructors.md
  website/docs/context.md
  website/docs/exports.md
  website/docs/getting_started.md
  website/docs/interpolator.md
  website/docs/intro.md
  website/docs/laziness.md
  website/docs/lifting.md
  website/docs/logging.md
  website/docs/missing.md
  website/docs/templates.md
  website/docs/tutorial.md
  website/docusaurus.config.js
  website/package-lock.json
  website/sidebars.js
  website/src/components/HomepageFeatures/index.js
  website/src/components/HomepageFeatures/styles.module.css
  website/src/components/Version/index.js
  website/src/pages/index.js
  website/src/pages/index.module.css
  website/src/remark/codeblockVersion.js
  website/static/img/scala-logo.svg
Labels: area/docs, impact/first-48

#175 Update README, add CONTRIBUTING and CoC
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  README.md
  template/README.md
Labels: kind/improvement, impact/usability, area/docs, impact/first-48

#172 Prepare templates before release
  .github/workflows/ci.yml
  .github/workflows/templates.yml
  .gitignore
  Justfile
  README.md
  template/default/project.scala
  template/kubernetes/project.scala
  templates/README.md
  templates/aws/Main.scala
  templates/aws/Pulumi.yaml
  templates/aws/project.scala
  templates/default/Main.scala
  templates/default/Pulumi.yaml
  templates/default/project.scala
  templates/kubernetes/Main.scala
  templates/kubernetes/Pulumi.yaml
  templates/kubernetes/project.scala
Labels: kind/improvement, area/docs, impact/first-48

#191 Update docs and website
  website/docs/apply_methods.md
  website/docs/architecture.md
  website/docs/compiler_plugin.md
  website/docs/components.md
  website/docs/constructors.md
  website/docs/context.md
  website/docs/examples.md
  website/docs/exports.md
  website/docs/interpolator.md
  website/docs/intro.md
  website/docs/laziness.md
  website/docs/logging.md
  website/docs/missing.md
  website/docs/packages.md
  website/docs/templates.md
  website/docs/tutorial.md
Labels: area/docs, impact/first-48, size/S
